name: chem-ml-practice
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - joblib
  - rdkit
  - jupyterlab
  - notebook
  - ipykernel
  - pytorch
  - pip
  - pip:
      - deepchem
      - torch-geometric
