name: chem-ml-practice
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - rdkit
  - requests
  - jupyterlab
  - ipykernel
  - nbformat
  - nbclient
  - pip
  - pip:
      - torch
